# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: pydanticai_default
      conn_type: pydanticai
      conn_host: https://router.huggingface.co/v1
      conn_schema:
      conn_login:
      conn_password: hf_replace_with_your_token
      conn_port:
      conn_extra:
        model: openai:meta-llama/Llama-3.3-70B-Instruct:novita
    - conn_id: pydanticai_groundedness
      conn_type: pydanticai
      conn_host: https://router.huggingface.co/v1
      conn_schema:
      conn_login:
      conn_password: hf_replace_with_your_token
      conn_port:
      conn_extra:
        model: openai:meta-llama/Llama-3.3-70B-Instruct:novita
    - conn_id: slack_default
      conn_type: slackwebhook
      conn_host:
      conn_schema:
      conn_login:
      conn_password: https://hooks.slack.com/services/replace_with_your_webhook_path
      conn_port:
      conn_extra:
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
